name: (Privileged) Auto Assign

on:
  issues:
    types: [opened]
  # Don't use pull_request or pull_request_target here.
  # See auto-assign-pr-schedule.yaml for explanation.
  workflow_run:
    workflows: [ "Auto Assign PR" ]
    types:
    - completed

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    # DEBUG
    - name: Dump GitHub context
      env:
        PR_NUMBER: ${{ github.context.payload.workflow_run.pull_requests[0].number }}
      run: echo "$PR_NUMBER"
    - name: Auto-assign issue
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: bwplotka
        abortIfPreviousAssignees: true
