name: (Privileged) Auto Assign

on:
  issues:
    types: [opened]
  # Don't use pull_request or pull_request_target here.
  # See auto-assign-pr-schedule.yaml for explanation.
  workflow_run:
    workflows: [ "Auto Assign PR" ]
    types:
    - completed

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    # DEBUG
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
    # Correct
    - name: Auto-assign issue
      uses: pozil/auto-assign-issue@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ secrets.DEFAULT_ISSUE_ASSIGNEE }}
        abortIfPreviousAssignees: true
